# Generated by Django 3.2.4 on 2021-07-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210716_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processreport',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
