# Generated by Django 3.2.4 on 2021-07-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_processreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='supervisor_remarks',
            field=models.TextField(blank=True, default='--', null=True),
        ),
    ]
