# Generated by Django 3.2.4 on 2021-08-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_projectstatus_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='body',
        ),
    ]
